server:
  port: 8099
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

javax:
  persistence:
    schema-generation:
      scripts:
        create-source:
        action: drop-and-create
