server:
  port: 8099
spring:
  docker:
    compose:
      enabled: true
      file: HW28-Spring-web/src/main/resources/docker-compose.yaml
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB2
    username: usr
    password: pwd
    driverClassName: org.postgresql.Driver

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE