spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/project-work
    username: project-work
    password: project-work
  flyway:
    url: jdbc:postgresql://localhost:5430/project-work
    user: project-work
    password: project-work
    enabled: true
    locations: classpath:db
    baseline-on-migrate: true
    baseline-version: 0
#  jpa:
#    defer-datasource-initialization: false
#    database: postgresql
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE